// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stmortaqfatwwjvkerno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0bW9ydGFxZmF0d3dqdmtlcm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMDM0NTYsImV4cCI6MjA1Mzc3OTQ1Nn0.40sZeZrSqDxFJEKtLC4_O9btjWIgQ2sfgE0Of81jPOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);